sudo: required
services:
  - docker

before_install:
  - docker build -t bryanesmith/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bryanesmith/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "$APP_NAME"
  env: "$ENV_NAME"
  bucket_name: "$BUCKET_NAME"
  bucket_path: "$APP_NAME"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"